### ISSUE TITLE
Tcrdist working with sample data but not with my data

### ISSUE THREAD

**Issue by rutha32** [kmayerb/tcrdist3#94]
[tcrdist_alpha_sample.pdf](https://github.com/kmayerb/tcrdist3/files/13244328/tcrdist_alpha_sample.pdf)

Hi, tcrdist works fine when I use the sample data (dash.csv), but when I try it with other datasets, I'm getting errors. 

These are my columns: 'subject', 'epitope', 'count', 'v_a_gene', 'd_call', 'j_a_gene',
       'cdr3_a_aa', 'cdr3_a_nucseq', 'junction', 'decombinator_id', 'rev_comp',
       'productive', 'sequence_aa', 'cdr1_aa', 'cdr2_aa', 'chain', 'clone_id',
       'time'],
      dtype='object'

this is the error I get 
ValueError: zero-size array to reduction operation maximum which has no identity

**My code** 
import pandas as pd

file_path = r'C:\Users\pythonProject\ResearchProject\alpha_TCR_all_sample_100.csv'

df = pd.read_csv(file_path)

df.head()
from tcrdist.repertoire import TCRrep

tr = TCRrep(
    cell_df=df,
    organism='human',
    chains=['alpha'],
    db_file='alphabeta_gammadelta_db.tsv'
)

pw_alpha = tr.pw_alpha

Thanks

**Comment by kmayerb** [comment]
The most likely issue is that your V-gene names are not recognized. Do they
have allele level resolution? If not, you can add "*01" for approximate
result. V-genes must match one of the following values in the id columns --

https://github.com/kmayerb/tcrdist3/blob/master/tcrdist/db/alphabeta_gammadelta_db.tsv

Alternatively you can define cdr1_a_aa, cdr2_a_aa, pmhc_a_aa your
self instead of using TCRdist initialization to infer them:

see  `infer_cdrs = False.`

https://github.com/kmayerb/tcrdist3/blob/55d906b19e4c5038f5fdde843eb2edf8293efd88/tcrdist/repertoire.py#L14-L69

Can you provide 10 lines of your input data?

**Comment by rutha32** [comment]
Hi thanks for the reply, I got it working when I added the "*01". I removed the some of the columns and only kept the core columns count , v_a_gene, j_a_gene and cdr3_a_aa.
